---
- hosts: all
  # connection: local
  gather_facts: yes
  # become: yes
  become_method: sudo
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    local_home: "{{ lookup('env', 'HOME') }}"
    bin_path: "{{ local_home }}/.local/bin"
    data_dir: "{{ local_home }}/.local/share"
    os_family: "{{ ansible_os_family | lower }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"
    architecture: "{{ ansible_architecture }}"
  environment:
  roles:
    - role: base
    - role: debian
      when: ansible_facts['os_family'] == 'Debian'
    - role: macos
      when: ansible_facts['os_family'] == 'Darwin'
