repositories:
  ppa: []
  url:
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib"
    - "deb https://mega.nz/linux/MEGAsync/xUbuntu_18.04/ ./"
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://baltocdn.com/helm/stable/debian/ all main"
  key:
    - url: "https://dl.google.com/linux/linux_signing_key.pub"
    - url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    - url: "https://www.virtualbox.org/download/oracle_vbox.asc"
    - url: "https://mega.nz/linux/MEGAsync/xUbuntu_18.04/Release.key"
    - url: "https://download.docker.com/linux/ubuntu/gpg"
    - url: "https://packages.microsoft.com/keys/microsoft.asc"
    - url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    - url: "https://baltocdn.com/helm/signing.asc"

remote_executables:
  - name: helmfile
    url: "https://github.com/roboll/helmfile/releases/download/v0.144.0/helmfile_linux_amd64"
  - name: aws-iam-authenticator
    url: "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64"

shell:
  - curl https://pyenv.run | bash
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install && rm -rf aws*
